# Generated by Django 5.1.4 on 2024-12-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaqusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset', models.CharField(max_length=100)),
                ('portfolio_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio_2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_history',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='initial_value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='weights',
        ),
        migrations.RemoveField(
            model_name='portfolioallocation',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='portfolioallocation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='asset',
            name='allocation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.portfolioallocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioallocation',
            name='name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
