# Generated by Django 5.1.4 on 2024-12-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaqusapp', '0002_price_weight_remove_asset_price_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='allocation',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='value',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='value',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='portfolio_1',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='portfolio_2',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='portfolio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.asset'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.asset'),
        ),
        migrations.CreateModel(
            name='InitialInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abaqusapp.portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioAllocation',
        ),
    ]
